name: Deploy to AWS EC2

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish -c Release -r linux-x64 --self-contained false -o ./publish

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./publish/*"
          target: "/tmp/app_deploy"

      - name: Execute Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl stop kestrel-hardwarestore.service
            sudo rm -rf /var/www/hardwarestore/*
            sudo cp -r /tmp/app_deploy/publish/* /var/www/hardwarestore/
            sudo chown -R www-data:www-data /var/www/hardwarestore
            sudo systemctl start kestrel-hardwarestore.service
